GET http://127.0.0.1:3001/api/notes
Accept: application/json

###
GET http://127.0.0.1:3001/api/notes/347f2b0c-1e64-41d0-b135-2e60f7cb2547
Accept: application/json

###

GET http://127.0.0.1:3001/api/notes/banana
Accept: application/json


###
POST http://127.0.0.1:3001/api/notes
Content-Type: application/json

{
  "title": "New Note",
  "text": "Testing API"
}

###

POST http://127.0.0.1:3001/api/notes
Content-Type: application/json

{
  "title": "",
  "text": ""
}

###

PUT http://127.0.0.1:3001/api/notes/347f2b0c-1e64-41d0-b135-2e60f7cb2547
Content-Type: application/json

{
  "id": "36c94ebd-3ca5-4b08-b674-3051fcbc5b88",
  "title": "Changed.",
  "text": "Changed text."
}

###

PUT http://127.0.0.1:3001/api/notes/347f2b0c-1e64-41d0-b135-2e60f7cb2547
Content-Type: application/json

{
  "id": "banana",
  "title": "Changed title.",
  "text": "This shouldn't work."
}

###

PUT http://127.0.0.1:3001/api/notes/347f2b0c-1e64-41d0-b135-2e60f7cb2547
Content-Type: application/json

{
  "id": "347f2b0c-1e64-41d0-b135-2e60f7cb2547",
  "title": "",
  "text": "This shouldn't work."
}

###

DELETE http://127.0.0.1:3001/api/notes/5bacd1e8-74d4-401c-a154-2908a3b65999

###

DELETE http://127.0.0.1:3001/api/notes/banana